#!/usr/bin/env python3

"""
reactome list name - list ids of entities with name
reactome biopax id - download biopax of entity
reactome url - show the base API URL used

A reactome command line tool.

Some examples:
reactome hit SOX2
reactome diagram 504046
reactome list Apoptosis
reactome biopax 109581
"""

# see http://reactomews.oicr.on.ca:8080/ReactomeRESTfulAPI/ReactomeRESTFulAPI.html

import sys

import requests

URL="http://reactomews.oicr.on.ca:8080/ReactomeRESTfulAPI/RESTfulWS/"

def main(argv=None):
    if argv is None:
        argv = sys.argv

    g = globals()
    commands = [c for c in g.keys() if c.startswith("command_")]
    commands = [c.replace("command_", "") for c in commands]

    def command_show(arg):
        for cmd in commands:
            print("reactome", cmd)

    arg = argv[1:]
    if len(arg) < 1:
        return command_show(arg)
    command = arg[0]

    if command in commands:
        return g["command_" + command](arg)
    else:
        return command_show(arg)


def command_list(arg):
    name = arg[1]

    post("listByQuery/Pathway", data='name={}'.format(name))

def command_biopax(arg):
    id = arg[1]

    url = "biopaxExporter/Level2/{}".format(id)
    get_out(url)

def command_front(arg):
    species = arg[1]

    url = "frontPageItems/{}".format(species)
    get_out(url)

def command_hit(arg):
    genes = ",".join(arg[1:])
    post("queryHitPathways", genes)

def command_diagram(arg):
    import base64

    id = arg[1]
    response = plain("pathwayDiagram/{}/PNG".format(id))
    sys.stdout.buffer.write(base64.b64decode(response.content))

def command_species(arg):
    get_out("speciesList")

def command_url(arg):
    print(URL)

def post(url_path, data):
    response = requests.post(URL + url_path, data,
        headers={'Content-Type': 'text/plain'})

    sys.stdout.buffer.write(response.content)

def get(url_path, headers=None):
    if headers is None:
        headers={'Accept': 'application/json'}
    url = URL + url_path
    response = requests.get(url,
        headers=headers)
    return response

def get_out(*l, **k):
    response = get(*l, **k)

    sys.stdout.buffer.write(response.content)

def plain(url_path):
    return get(url_path, headers=dict())

if __name__ == '__main__':
    main()
